/**
 * The handful of token values that have to exist as TypeScript rather than as CSS.
 *
 * Normally no colour is ever typed outside `globals.css`, and `npm run house` fails the build if
 * one is. This file is the single declared exception, because two things need a literal before a
 * stylesheet exists: the `theme-color` meta tag, which paints mobile browser chrome before the
 * first paint, and the favicon, which is generated by a script.
 *
 * The house rules script checks that every hex in here also appears in `globals.css`, so the
 * exception cannot drift into a second palette.
 */

/** `--ink`. The page background, and what a phone paints its address bar. */
export const PAGE_INK = "#0a0c0f";

/** `--copper`. The origin leg, the focus ring, and the mark. */
export const SIGNAL_COPPER = "#e8743b";

/** `--fg`. Primary text, and the monoline mark on a light surface. */
export const SIGNAL_FG = "#eceff3";
